# Generated by Django 4.0.5 on 2022-06-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='reservation_cost',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='reservation_status',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='reservation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
