# Generated by Django 4.0.5 on 2022-06-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservations_reservation_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_date',
            field=models.DateField(),
        ),
    ]
