# Generated by Django 4.0.5 on 2022-06-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservations_reservation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tenniscourt',
            name='equipment_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenniscourt',
            name='city',
            field=models.CharField(choices=[('Białystok', 'Białystok'), ('Gdańsk', 'Gdańsk'), ('Kraków', 'Kraków'), ('Lublin', 'Lublin'), ('Olsztyn', 'Olsztyn'), ('Poznań', 'Poznań'), ('Warszawa', 'Warszawa'), ('Wrocław', 'Wrocaław')], max_length=24),
        ),
    ]
