# Generated by Django 4.0.5 on 2022-07-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservations_reservation_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='reservation_start',
            field=models.TimeField(),
        ),
    ]
