# Generated by Django 4.0.5 on 2022-06-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_adminpanel_tenniscourt_equipment_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenniscourt',
            name='short_description',
            field=models.CharField(default='', max_length=128),
        ),
    ]
