# Generated by Django 4.0.5 on 2022-07-03 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('reservations', '0005_alter_reservations_reservation_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
