# Generated by Django 4.0.5 on 2022-06-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_rename_object_reservations_court_object_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='court_object',
            new_name='court',
        ),
    ]
